name: Sync to Gitee

on:
  push:
    branches: ['**']
    tags: ['**']
  delete:
    branches: ['**']
    tags: ['**']

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:jsshwqz/patent-hub.git
          destination-repo: git@gitee.com:jsshwqz/patent-hub.git
